/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewInicio;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import viewDirector.MainWindowDirector;
import viewPelicula.MainWindowPeli;
import viewSerie.MainWindowSerie;
import viewTransmisiones.MainWindowTransmisiones;
import viewUsuario.MainWindowUsuario;

/**
 *
 * @author RUYIS
 */
public class VentanaInicial extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInicial
     */
    public VentanaInicial() {
        initComponents();
        this.getContentPane().setBackground(Color.black);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension frameSize  = getSize();
        setLocation((screenSize.width  - frameSize.width)  / 2, 
                    (screenSize.height - frameSize.height) / 2);

        //Color JPanel
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonPeli = new javax.swing.JButton();
        jButtonSerie = new javax.swing.JButton();
        jButtonDirector = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonTransmisiones = new javax.swing.JButton();
        jButtonUsuario = new javax.swing.JButton();
        jLabelusuicon = new javax.swing.JLabel();
        jLabelSerieicon = new javax.swing.JLabel();
        jLabelpeliicon = new javax.swing.JLabel();
        jLabeltransmiicon = new javax.swing.JLabel();
        jLabeldirecicon = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setIconImage(getIconImage());
        setIconImages(getIconImages());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonPeli.setBackground(new java.awt.Color(204, 204, 204));
        jButtonPeli.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jButtonPeli.setForeground(new java.awt.Color(0, 0, 153));
        jButtonPeli.setText("Peliculas");
        jButtonPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPeliActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPeli, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        jButtonSerie.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSerie.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jButtonSerie.setForeground(new java.awt.Color(0, 0, 153));
        jButtonSerie.setText("Series");
        jButtonSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSerieActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSerie, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 350, -1, -1));

        jButtonDirector.setBackground(new java.awt.Color(204, 204, 204));
        jButtonDirector.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jButtonDirector.setForeground(new java.awt.Color(0, 0, 153));
        jButtonDirector.setText("Directores");
        jButtonDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDirectorActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDirector, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 450, -1, -1));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Britannic Bold", 1, 68)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Welcome");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, -1, 66));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Britannic Bold", 1, 88)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 0, 0));
        jLabel2.setText("Black Corner");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, 64));

        jButtonTransmisiones.setBackground(new java.awt.Color(204, 204, 204));
        jButtonTransmisiones.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jButtonTransmisiones.setForeground(new java.awt.Color(0, 0, 153));
        jButtonTransmisiones.setText("Transmisiones");
        jButtonTransmisiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransmisionesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTransmisiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 570, 306, -1));

        jButtonUsuario.setBackground(new java.awt.Color(204, 204, 204));
        jButtonUsuario.setFont(new java.awt.Font("Britannic Bold", 1, 24)); // NOI18N
        jButtonUsuario.setForeground(new java.awt.Color(0, 0, 153));
        jButtonUsuario.setText("Usuarios");
        jButtonUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, -1, -1));

        jLabelusuicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usuario.png"))); // NOI18N
        jLabelusuicon.setText("jLabel4");
        getContentPane().add(jLabelusuicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 410, 40, -1));

        jLabelSerieicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/video.png"))); // NOI18N
        jLabelSerieicon.setText("jLabel3");
        getContentPane().add(jLabelSerieicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 40, -1));

        jLabelpeliicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/camera.png"))); // NOI18N
        jLabelpeliicon.setText("jLabel3");
        getContentPane().add(jLabelpeliicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 40, -1));

        jLabeltransmiicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cinema.png"))); // NOI18N
        jLabeltransmiicon.setText("jLabel3");
        getContentPane().add(jLabeltransmiicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 530, 40, -1));

        jLabeldirecicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/director.png"))); // NOI18N
        jLabeldirecicon.setText("jLabel3");
        getContentPane().add(jLabeldirecicon, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 410, 40, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/2.jpg"))); // NOI18N
        jLabelFondo.setText("jLabel3");
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 0, 1180, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPeliActionPerformed
        new MainWindowPeli();
        //new VentanaPelicula().setVisible(true);
    }//GEN-LAST:event_jButtonPeliActionPerformed

    private void jButtonSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSerieActionPerformed
        new MainWindowSerie();
        //new VentanaSerie().setVisible(true);
    }//GEN-LAST:event_jButtonSerieActionPerformed

    private void jButtonDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDirectorActionPerformed
        new MainWindowDirector();
        //new VentanaDirector().setVisible(true);
    }//GEN-LAST:event_jButtonDirectorActionPerformed

    private void jButtonTransmisionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransmisionesActionPerformed
        new MainWindowTransmisiones();
        //new VentanaUsuario().setVisible(true);
    }//GEN-LAST:event_jButtonTransmisionesActionPerformed

    private void jButtonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUsuarioActionPerformed
        new MainWindowUsuario();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDirector;
    private javax.swing.JButton jButtonPeli;
    private javax.swing.JButton jButtonSerie;
    private javax.swing.JButton jButtonTransmisiones;
    private javax.swing.JButton jButtonUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelSerieicon;
    private javax.swing.JLabel jLabeldirecicon;
    private javax.swing.JLabel jLabelpeliicon;
    private javax.swing.JLabel jLabeltransmiicon;
    private javax.swing.JLabel jLabelusuicon;
    // End of variables declaration//GEN-END:variables
}
